"""Single tuning surface for all caps and thresholds."""

LIMITS = {
    "MAX_FILE_SIZE_MB": 200,
    "SAMPLE_THRESHOLD_ROWS": 500_000,
    "SAMPLE_TARGET_ROWS": 100_000,
    "MAX_COLUMNS": 500,
    "CATEGORY_CONVERSION_THRESHOLD": 0.5,
    "CHUNK_SIZE": 50_000,
    "MAX_UPLOADS_PER_SESSION": 20,
    "SCATTER_WEBGL_THRESHOLD": 5_000,
    "SCATTER_SAMPLE_THRESHOLD": 100_000,
    "SCATTER_SAMPLE_SIZE": 100_000,
    "PAIR_PLOT_MAX_COLUMNS": 8,
    "CORR_MASK_DEFAULT": 0.0,
}
